version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: "Image Information"
          command: printf "\nKernel:\n " && uname -a && printf "\n\nMemory:\n " && free -h && printf "\n\nStorage:\n" && df -h
      - run:
          name: "Chmod Permissions"
          command: sudo chmod +x ./gradlew
      - run:
          name: "Download Dependencies"
          command: ./gradlew dependencyUpdates
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "kite/build.gradle" }}-{{ checksum  "sample/build.gradle" }}
      - run:
          name: "Build Modules"
          command: ./gradlew build
      - run:
          name: "dependencyUpdates"
          command: ./gradlew dependencyUpdates
      - run:
          name: "Run Gradle check"
          command: ./gradlew check
      - run:
          name: "Run Tests"
          command: ./gradlew lint test